[package]
name = "kal-time"
version = "%%version%%"
edition = "2021"
authors = ["Valentin Lab <valentin.lab@kalysto.org>"]
description = "Rust library for parsing human-friendly time and timespan expressions"
license = "MIT"
repository = "https://github.com/0k/kal-time"
readme = "README.md"
keywords = ["time", "datetime", "parsing", "chrono"]
categories = ["date-and-time", "parsing"]

[dependencies]
chrono = { version = "0.4.31" }
chrono-english = "0.1"
fern = "0.6.2"
log = "0.4.20"
lazy_static = "1.4.0"
